### ISSUE TITLE
Add a configuration switch to automatically mark all tests

### ISSUE THREAD

**Issue by azmeuk** [RKrahl/pytest-dependency#7]
The current documentation describe this usecase:
```python
@pytest.mark.dependency()
def test_a():
    pass

@pytest.mark.dependency(depends=["test_a"])
def test_b():
    pass
```

It would be great to avoid marking `test_a`:
```python
def test_a():
    pass

@pytest.mark.dependency(depends=["test_a"])
def test_b():
    pass
```
What do you think?

**Comment by RKrahl** [comment]
This won't work, I'm afraid.  The problem is that I need to record the outcome of `test_a` so that the dependency marker for `test_b` can check this result and decide whether to skip or not to skip `test_b`.  The marker does just this: recording the outcome of the respective  test in the internal structures of pytest-dependency.  So I need it also on `test_a`.

**Comment by RKrahl** [comment]
Sorry, my last comment was wrong.  It could be implemented as you suggest.

However, I don't like this behavior to be the default.  I'd prefer to have the dependencies explicitly be marked.  Furthermore, this behavior would mean that internal data structures of pytest get modified even for packages that don't even use pytest-dependency, if only pytest-dependency is installed.

I will rather add a configuration switch `automark_dependency` to be set in the ini file.  If set to `False`, the default, the current behavior will be retained, e.g. dependencies will need to be marked explicitly.  If set to `True`, it will have the same effect as if all test are implicitly decorated with `@pytest.mark.dependency()`.

**Comment by azmeuk** [comment]
The switch would be a pretty good solution indeed!
